### ISSUE TITLE
Too long functions

### ISSUE THREAD

**Issue by AlexSkorupsky** [nataliapachva/InheritanceCar#2]
#I think some methods can be divided into several methods
For example:

public List<IAutomobile> InpuList()
        {
            List<IAutomobile> automobiles = new List<IAutomobile>();
            List<IAutomobile> baseAutomobiles = GetBaseAutomobiles();
            automobiles.AddRange(baseAutomobiles);
            Console.WriteLine("Enter size of cars(there is a basic list of machines, if you do not want to add to the list " +
                              "enter the size of the cars 0): ");
            string str = Console.ReadLine();
            int count = Convert.ToInt32(str);
            if (count != 0)
            {
                ShowHead();
                for (int i = 0; i < count; i++)
                {
                    string line = Console.ReadLine();
                    IAutomobile car = Parse(line);
                    automobiles.Add(car);
                }
            }
            return automobiles;
        }

**Comment by nataliapachva** [comment]
fixed
